### ISSUE TITLE
service/tickets/{id}

### ISSUE THREAD

**Issue by dustinaevans** [markciecior/ConnectPyse#4]
response is:
Server message:{
  "code": "ConnectWiseApi",
  "message": "Length cannot be less than zero.\r\nParameter name: length",
  "errors": null
}

**Comment by markciecior** [comment]
@dustinaevans Can you show me the entire request you're making?  Give me a few snippets of code to see what's going on.

**Comment by dustinaevans** [comment]
Sorry about the delay.

`import os,re
import slack
from connectpyse.service import tickets_api

client = slack.WebClient(token='xoxb-blablablablabla')
AUTH = {'Authorization':'Basic blablabla==','clientId':'blablabla'}
URL = 'https://connect.turnkeysol.com/v4_6_release/apis/3.0'

ticketsAPI = tickets_api.TicketsAPI(url=URL,auth=AUTH)

@slack.RTMClient.run_on(event='message')
def cw_respond(**payload):
    data = payload['data']
    web_client = payload['web_client']
    rtm_client = payload['rtm_client']
    message = data.get('text',[])
    match = re.match(r'\b(\d{6,8}(?!\d))',message)
    if match:
        # print(match[0])
        print("Ticket:",match[0])
        ticket = ticketsAPI.get_ticket_by_id(match[0])
        client.chat_postMessage(channel='#random',text="Hello world!")


rtm_client = slack.RTMClient(token='xoxb-blablabla')
rtm_client.start()`

The bot listens for ambient messages and looks up any number that might be a ticket number and prints the ticket to 

`python3 archimedes.py
Ticket: 1770851
Traceback (most recent call last):
  File "archimedes.py", line 26, in <module>
    rtm_client.start()
  File "/home/dustine/.local/lib/python3.6/site-packages/slack/rtm/client.py", line 198, in start
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/dustine/.local/lib/python3.6/site-packages/slack/rtm/client.py", line 339, in _connect_and_read
    await self._read_messages()
  File "/home/dustine/.local/lib/python3.6/site-packages/slack/rtm/client.py", line 390, in _read_messages
    await self._dispatch_event(event, data=payload)
  File "/home/dustine/.local/lib/python3.6/site-packages/slack/rtm/client.py", line 440, in _dispatch_event
    self._execute_in_thread(callback, data)
  File "/home/dustine/.local/lib/python3.6/site-packages/slack/rtm/client.py", line 465, in _execute_in_thread
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "archimedes.py", line 21, in cw_respond
    ticket = ticketsAPI.get_ticket_by_id(match[0])
  File "/home/dustine/.local/lib/python3.6/site-packages/connectpyse/service/tickets_api.py", line 23, in get_ticket_by_id
    return super()._get_by_id(ticket_id)
  File "/home/dustine/.local/lib/python3.6/site-packages/connectpyse/cw_controller.py", line 52, in _get_by_id
    an_instance = self._class(getattr(self, self.module).get(the_id=item_id, user_headers=self.basic_auth))
  File "/home/dustine/.local/lib/python3.6/site-packages/connectpyse/restapi.py", line 170, in get
    resp.text)
connectpyse.restapi.ApiError: GET tickets Return code: 500

Server message:{
  "code": "ConnectWiseApi",
  "message": "Length cannot be less than zero.\r\nParameter name: length",
  "errors": null
}`

**Comment by dustinaevans** [comment]
@markciecior I know you are probably busy with other things, but any thoughts on this?

**Comment by markciecior** [comment]
The error is coming from your ConnectWise instance.  ConnectPyse is
generating the ApiError because the HTTP return code isn't 200.

Try making a GET request to this URL directly to see what happens:
https://<OUR_CW_URL>/v4_6_release/apis/3.0/service/tickets/1770851

Here's the equivalent python code that Postman generated for me:

import requests

url = "https://<YOUR_CW_URL>/v4_6_release/apis/3.0/service/tickets/1770851"

payload = {}
headers = {
  'Authorization': 'Basic Y2Fy BLAH BLAH BLAH BLAH U4=',
  'Content-Type': 'application/json',
  'clientId': '{{CLIENT_ID}}',
}

response = requests.request("GET", url, headers=headers, data = payload)

print(response.text.encode('utf8'))
